"""Secondary structure assignment.

The original MATLAB tool requires a STRIDE-format ``struct.txt`` file
generated by running the external STRIDE program on the PDB file, and
treats a residue as "structured" for the WSME model if STRIDE assigns it
H (alpha helix), E (strand) or G (3-10 helix).

This module provides a self-contained, dependency-free geometric
approximation of that H/E/G classification directly from backbone
coordinates (a Ramachandran phi/psi classification with short-run
smoothing), so the tool does not require installing STRIDE/DSSP.  If you
do have STRIDE or DSSP output, use ``secondary_structure_from_codes`` to
get bit-identical behavior to the original tool instead.
"""

from __future__ import annotations

import numpy as np

from .structure import Structure

# Ramachandran regions (degrees), broad boxes tuned to be permissive
# enough to capture real helix/strand geometry while excluding loops.
_HELIX_PHI = (-100.0, -30.0)
_HELIX_PSI = (-77.0, -5.0)
_STRAND_PHI = (-180.0, -45.0)
_STRAND_PSI_POS = (90.0, 180.0)
_STRAND_PSI_NEG = (-180.0, -150.0)

# Minimum consecutive-residue run length to accept a Ramachandran-region
# streak as real secondary structure (removes single-residue noise).
_MIN_HELIX_RUN = 3
_MIN_STRAND_RUN = 2

HEG_CODES = {"H", "E", "G"}


def _backbone_atoms(structure: Structure):
    """Return per-residue N, CA, C coordinates (NaN where missing)."""
    nres = structure.nres
    n = np.full((nres, 3), np.nan)
    ca = np.full((nres, 3), np.nan)
    c = np.full((nres, 3), np.nan)
    for name, xyz, ridx in zip(structure.atom_name, structure.coord, structure.atom_resindex):
        if name == "N":
            n[ridx] = xyz
        elif name == "CA":
            ca[ridx] = xyz
        elif name == "C":
            c[ridx] = xyz
    return n, ca, c


def _dihedral(p0, p1, p2, p3):
    """Dihedral angle (degrees) for arrays of points, shape (n, 3) each."""
    b0 = p0 - p1
    b1 = p2 - p1
    b2 = p3 - p2
    b1n = b1 / np.linalg.norm(b1, axis=-1, keepdims=True)
    v = b0 - (np.sum(b0 * b1n, axis=-1, keepdims=True)) * b1n
    w = b2 - (np.sum(b2 * b1n, axis=-1, keepdims=True)) * b1n
    x = np.sum(v * w, axis=-1)
    y = np.sum(np.cross(b1n, v) * w, axis=-1)
    return np.degrees(np.arctan2(y, x))


def _in_range(x, lo, hi):
    return (x >= lo) & (x <= hi)


def _smooth_runs(mask: np.ndarray, min_run: int) -> np.ndarray:
    out = mask.copy()
    n = len(mask)
    i = 0
    while i < n:
        if mask[i]:
            j = i
            while j < n and mask[j]:
                j += 1
            if (j - i) < min_run:
                out[i:j] = False
            i = j
        else:
            i += 1
    return out


def assign_secondary_structure(structure: Structure) -> np.ndarray:
    """Geometric H/E/G classification. Returns bool array, shape (nres,).

    True marks a residue as helix/strand/3-10-helix-like ("structured" in
    the WSME sense); False marks coil/turn/loop.
    """
    n, ca, c = _backbone_atoms(structure)
    nres = structure.nres

    phi = np.full(nres, np.nan)
    psi = np.full(nres, np.nan)
    if nres > 1:
        valid_phi = ~(np.isnan(c[:-1]).any(1) | np.isnan(n[1:]).any(1) | np.isnan(ca[1:]).any(1) | np.isnan(c[1:]).any(1))
        idx = np.where(valid_phi)[0]
        if len(idx):
            phi[idx + 1] = _dihedral(c[idx], n[idx + 1], ca[idx + 1], c[idx + 1])
        valid_psi = ~(np.isnan(n[:-1]).any(1) | np.isnan(ca[:-1]).any(1) | np.isnan(c[:-1]).any(1) | np.isnan(n[1:]).any(1))
        idx = np.where(valid_psi)[0]
        if len(idx):
            psi[idx] = _dihedral(n[idx], ca[idx], c[idx], n[idx + 1])

    with np.errstate(invalid="ignore"):
        helix = _in_range(phi, *_HELIX_PHI) & _in_range(psi, *_HELIX_PSI)
        strand = _in_range(phi, *_STRAND_PHI) & (
            _in_range(psi, *_STRAND_PSI_POS) | _in_range(psi, *_STRAND_PSI_NEG)
        )
    helix = np.nan_to_num(helix, nan=False).astype(bool)
    strand = np.nan_to_num(strand, nan=False).astype(bool)

    helix = _smooth_runs(helix, _MIN_HELIX_RUN)
    strand = _smooth_runs(strand & ~helix, _MIN_STRAND_RUN)

    return helix | strand


def secondary_structure_from_codes(codes: str) -> np.ndarray:
    """Map an explicit per-residue SS code string (e.g. from STRIDE/DSSP,
    one char per residue drawn from H/E/G/other) to the structured mask.
    """
    return np.array([c in HEG_CODES for c in codes], dtype=bool)
