"""
Real, non-synthetic run of the full 4-tool pipeline.

GPR68 itself is not obtainable in this sandbox (RCSB / AlphaFold DB / GPCRdb
are all network-blocked here, and the GPR68 structures a previous session
downloaded live in that session's now-gone scratchpad). As agreed with the
user, this instead uses the mu-opioid receptor crystal structure (PDB 4DKL)
already bundled in this repo as `examples/data/gpcr_landscapes_reference/gpcr9i.pdb`
(see README_wsme_gpcr.md) as a stand-in class-A GPCR, so the pipeline itself
-- as opposed to any GPR68-specific biology -- can be exercised end to end
with real tools and real physics rather than synthetic numbers.

What's real vs. substituted, explicitly:
  * Tool 1 (protonation from pKa + pH): REAL. wsme_gpcr.pka_predictor runs
    PROPKA3 on the actual structure to get structure-aware pKa values (not
    free-solution defaults), then Henderson-Hasselbalch gives the fractional
    protonation of each titratable site at a chosen pH.
  * Tool 2 (AlphaFold/ColabFold ensemble): SUBSTITUTED. Actually running
    ColabFold needs a GPU and network access to the MMseqs2 MSA server,
    neither available here (gpcr_ensemble's own README says as much: "not
    covered by tests since it requires GPU compute and cannot run in this
    environment"). In its place, a small ensemble is generated by displacing
    the reference structure along its lowest-frequency Calpha ANM normal
    modes (a standard, legitimate elastic-network ensemble-generation
    method) -- this is disclosed, not passed off as an AlphaFold ensemble.
    Tool 2's *real* code (gpcr_ensemble.activation_state.tm3_tm6_distance)
    is still used to compute the activation microswitch on every conformer.
  * Tool 3 (Gibbs free energy): REAL. gibbs/gpcr_gibbs_energy.py's actual
    AMBER ff14SB + GBn2 + RRHO pipeline (OpenMM + PDBFixer) is run on every
    conformer at every pH -- real minimization, real force field, real
    entropy estimate.
  * Tool 4 (this pipeline's landscape tool): REAL, unmodified.

Run at two pH values (7.4 and 6.0) so a pH-sensitive shift in the landscape
-- the interesting question for a proton-sensing receptor like GPR68 -- is
at least visible in the analysis machinery, even on a receptor that isn't
itself a proton sensor.

This is slow (~80s per Gibbs run x N_CONFORMERS x 2 pH values) because it is
doing real OpenMM minimizations, not toy computations. Run with:

    PYTHONPATH=.:gibbs python examples/gpcr_pipeline_real_demo.py
"""

from __future__ import annotations

import json
import math
import sys
import time
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from Bio.PDB import PDBIO, PDBParser
from Bio.SeqUtils import seq1

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "gibbs"))

from gpcr_ensemble.activation_state import DEFAULT_THRESHOLDS, classify_model, tm3_tm6_distance  # noqa: E402
from gpcr_energy_landscapes import pipeline as landscape_pipeline  # noqa: E402
from gpcr_energy_landscapes import plotting  # noqa: E402
import gpcr_gibbs_energy as gibbs_tool  # noqa: E402
from wsme_gpcr.pka_predictor import predict_pka_propka  # noqa: E402

REFERENCE_PDB = REPO_ROOT / "examples" / "data" / "gpcr_landscapes_reference" / "gpcr9i.pdb"
OUT_DIR = Path(__file__).resolve().parent / "output" / "real_demo"
N_CONFORMERS = 5
PH_VALUES = [7.4, 6.0]
RNG = np.random.default_rng(7)

# ----------------------------------------------------------------------------
# Tool 1: real structure-aware pKa prediction (PROPKA3)
# ----------------------------------------------------------------------------
FREE_SOLUTION_PKA = {"ASP": 3.9, "GLU": 4.1, "HIS": 6.0, "LYS": 10.5, "ARG": 12.5, "CYS": 8.3, "TYR": 10.1}
_ACID_RESNAMES = {"ASP", "GLU", "CYS", "TYR"}  # protonated (neutral) at low pH


def frac_protonated(pka_value, ph, acid=True):
    """Henderson-Hasselbalch fractional protonation."""
    if acid:
        return 1.0 / (1.0 + 10 ** (ph - pka_value))
    return 1.0 / (1.0 + 10 ** (pka_value - ph))


def run_tool1_protonation(structure, pdb_path, chain_id="A"):
    print("[tool 1] Running PROPKA3 structure-aware pKa prediction...", flush=True)
    pka = predict_pka_propka(pdb_path, chain=chain_id)
    print(f"[tool 1] Got pKa for {len(pka)} titratable groups.")

    resname_by_num = {r.id[1]: r.get_resname() for r in structure[0][chain_id] if r.id[0] == " "}
    shifts = []
    for resnum, pka_value in pka.items():
        resname = resname_by_num.get(resnum)
        baseline = FREE_SOLUTION_PKA.get(resname)
        if baseline is None:
            continue
        shifts.append((resnum, resname, pka_value, pka_value - baseline))
    shifts.sort(key=lambda t: -abs(t[3]))

    print("[tool 1] Largest structure-induced pKa shifts from free-solution baseline (top 8):")
    for resnum, resname, pka_value, shift in shifts[:8]:
        acid = resname in _ACID_RESNAMES
        f74 = frac_protonated(pka_value, 7.4, acid=acid)
        f60 = frac_protonated(pka_value, 6.0, acid=acid)
        print(
            f"    {resname}{resnum}: predicted pKa={pka_value:.2f} "
            f"(baseline {FREE_SOLUTION_PKA[resname]:.1f}, shift {shift:+.2f}); "
            f"protonated fraction pH7.4={f74:.2f} pH6.0={f60:.2f}"
        )
    return pka


# ----------------------------------------------------------------------------
# Tool 2 substitute: Calpha ANM ensemble generation (+ tool 2's real activation-state code)
# ----------------------------------------------------------------------------
def find_conserved_motifs(structure, chain_id="A"):
    """Auto-detect the DRY-motif Arg (TM3, 3.50) and NPxxY-motif Tyr (TM7, 7.53)
    directly from sequence, since this bundled structure's residue numbering
    doesn't correspond to any public GPCR numbering database."""
    chain = structure[0][chain_id]
    residues = [r for r in chain if r.id[0] == " "]
    resnums = [r.id[1] for r in residues]
    seq = "".join(seq1(r.get_resname()) for r in residues)

    dry_idx = seq.find("DRY")
    if dry_idx == -1:
        dry_idx = seq.find("ERY")  # common class-A variant
    if dry_idx == -1:
        raise ValueError("Could not find a DRY/ERY motif in the sequence")
    arg_resnum = resnums[dry_idx + 1]

    import re

    npxxy_match = re.search("N P..Y".replace(" ", ""), seq)
    if npxxy_match is None:
        raise ValueError("Could not find an NPxxY motif in the sequence")
    tyr_resnum = resnums[npxxy_match.start() + 4]

    return arg_resnum, tyr_resnum


def find_ionic_lock_partner(structure, arg_resnum, chain_id="A", min_seq_sep=15, max_dist=15.0):
    """Nearest Asp/Glu sidechain (by closest heavy-atom distance) to the DRY-Arg's
    guanidinium group, excluding immediate sequence neighbors -- an automatic,
    structure-based stand-in for the literature TM6 ionic-lock partner (~6.30)."""
    chain = structure[0][chain_id]
    arg_res = next(r for r in chain if r.id[1] == arg_resnum)
    guanidinium = np.array([a.coord for a in arg_res if a.get_name() in ("NH1", "NH2", "NE", "CZ")])

    best_resnum, best_dist = None, np.inf
    for res in chain:
        if res.id[0] != " " or res.get_resname() not in ("ASP", "GLU"):
            continue
        if abs(res.id[1] - arg_resnum) < min_seq_sep:
            continue
        coords = np.array([a.coord for a in res if a.element != "H"])
        d = np.linalg.norm(guanidinium[:, None, :] - coords[None, :, :], axis=-1).min()
        if d < best_dist:
            best_dist, best_resnum = d, res.id[1]
    if best_resnum is None or best_dist > max_dist:
        return None
    return best_resnum


def build_ca_anm_modes(ca_coords, cutoff_ang=15.0, gamma=1.0):
    """Same elastic-network Hessian as gibbs.gpcr_gibbs_energy.anm_frequencies,
    but returns eigenvectors too (needed to actually displace structures, not
    just report their frequencies)."""
    n = len(ca_coords)
    hessian = np.zeros((3 * n, 3 * n))
    for i in range(n):
        for j in range(i + 1, n):
            d_vec = ca_coords[i] - ca_coords[j]
            d = np.linalg.norm(d_vec)
            if d > cutoff_ang:
                continue
            block = -gamma * np.outer(d_vec, d_vec) / (d * d)
            hessian[3 * i : 3 * i + 3, 3 * j : 3 * j + 3] += block
            hessian[3 * j : 3 * j + 3, 3 * i : 3 * i + 3] += block
            hessian[3 * i : 3 * i + 3, 3 * i : 3 * i + 3] -= block
            hessian[3 * j : 3 * j + 3, 3 * j : 3 * j + 3] -= block
    eigvals, eigvecs = np.linalg.eigh(hessian)
    # drop the 6 near-zero trans/rot modes
    return eigvals[6:], eigvecs[:, 6:]


def generate_anm_ensemble(structure, chain_id, n_conformers, out_dir, n_modes=10, target_rmsd_ang=0.8):
    chain = structure[0][chain_id]
    residues = [r for r in chain if r.id[0] == " "]
    ca_coords = np.array([r["CA"].coord for r in residues])
    _, eigvecs = build_ca_anm_modes(ca_coords)

    out_dir.mkdir(parents=True, exist_ok=True)
    conformer_paths = {}
    writer = PDBIO()

    for k in range(n_conformers):
        amplitudes = RNG.normal(0, 1, n_modes)
        displacement = np.zeros_like(ca_coords)
        for m in range(n_modes):
            mode_vec = eigvecs[:, m].reshape(-1, 3)
            displacement += amplitudes[m] * mode_vec
        # rescale to a fixed target Calpha RMSD so every conformer is a
        # comparably sized step away from the reference structure
        rmsd = np.sqrt((displacement**2).sum(axis=1).mean())
        displacement *= target_rmsd_ang / rmsd

        conf_structure = structure.copy()
        conf_chain = conf_structure[0][chain_id]
        conf_residues = [r for r in conf_chain if r.id[0] == " "]
        for res, shift in zip(conf_residues, displacement):
            for atom in res:
                atom.coord = atom.coord + shift

        sid = f"anm_{k:02d}"
        path = out_dir / f"{sid}.pdb"
        writer.set_structure(conf_structure)
        writer.save(str(path))
        conformer_paths[sid] = path

    return conformer_paths


# ----------------------------------------------------------------------------
# Tool 3: real Gibbs free energy via the actual gibbs tool
# ----------------------------------------------------------------------------
def run_tool3_gibbs(pdb_path, ph):
    argv = [
        str(pdb_path),
        "--chains", "A",
        "--ph", str(ph),
        "--entropy-method", "ca-anm",
        "--minimize-iterations", "150",
        "--no-hbond-analysis",
    ]
    args = gibbs_tool.parse_args(argv)
    result = gibbs_tool.run(args)
    return result["G_kcal"]


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure("gpcr9i", str(REFERENCE_PDB))

    arg_resnum, tyr_resnum = find_conserved_motifs(structure)
    partner_resnum = find_ionic_lock_partner(structure, arg_resnum)
    print(f"Auto-detected DRY-motif Arg (TM3): resnum {arg_resnum}")
    print(f"Auto-detected NPxxY-motif Tyr (TM7): resnum {tyr_resnum}")
    print(f"Auto-detected ionic-lock partner (nearest Asp/Glu): resnum {partner_resnum}")

    pka = run_tool1_protonation(structure, REFERENCE_PDB)

    print(f"\n[tool 2-substitute] Generating {N_CONFORMERS} ANM-displaced conformers...")
    ensemble_dir = OUT_DIR / "ensemble"
    conformer_paths = generate_anm_ensemble(structure, "A", N_CONFORMERS, ensemble_dir)

    # Reuse tool 2's real activation-state classification on each conformer
    cv1_by_sid = {}
    cv2_by_sid = {}
    state_by_sid = {}
    for sid, path in conformer_paths.items():
        conf = parser.get_structure(sid, str(path))
        chain = conf[0]["A"]
        ca_coords = {r.id[1]: r["CA"].coord for r in chain if r.id[0] == " "}
        d_lock = tm3_tm6_distance(ca_coords, arg_resnum, partner_resnum) if partner_resnum else np.nan
        cv1_by_sid[sid] = d_lock
        tyr_res = next(r for r in chain if r.id[1] == tyr_resnum)
        arg_res = next(r for r in chain if r.id[1] == arg_resnum)
        cv2_by_sid[sid] = float(np.linalg.norm(tyr_res["CA"].coord - arg_res["CA"].coord))
        label, _ = classify_model(ca_coords, arg_resnum, partner_resnum, DEFAULT_THRESHOLDS) if partner_resnum else ("n/a", None)
        state_by_sid[sid] = label

    print(f"[tool 2-substitute] Activation-state labels: {state_by_sid}")

    all_results = {}
    for ph in PH_VALUES:
        print(f"\n[tool 3] Running real Gibbs free-energy calculations at pH {ph} "
              f"({N_CONFORMERS} conformers, ~80s each)...")
        energies = {}
        t0 = time.time()
        for i, (sid, path) in enumerate(conformer_paths.items()):
            g = run_tool3_gibbs(path, ph)
            energies[sid] = g
            print(f"  [{i+1}/{N_CONFORMERS}] {sid}: G = {g:.2f} kcal/mol "
                  f"(elapsed {time.time()-t0:.0f}s)", flush=True)
        all_results[ph] = energies

        energies_df = pd.DataFrame(
            {"structure_id": list(energies.keys()), "gibbs_kcal_mol": list(energies.values())}
        ).set_index("structure_id")
        cv_table = pd.DataFrame(
            {
                "structure_id": list(conformer_paths.keys()),
                "ionic_lock_like": [cv1_by_sid[s] for s in conformer_paths],
                "npxxy_dry_distance": [cv2_by_sid[s] for s in conformer_paths],
            }
        ).set_index("structure_id")
        merged = landscape_pipeline.merge_with_energies(cv_table, energies_df)
        merged.to_csv(OUT_DIR / f"merged_ph{ph}.csv")

        landscape1d = landscape_pipeline.build_1d_landscape(merged, "ionic_lock_like", method="kde", grid_size=100)
        fig, ax = plt.subplots(figsize=(5, 4))
        plotting.plot_1d_landscape(landscape1d, cv_label="DRY-Arg <-> ionic-lock-partner distance (Å)", ax=ax)
        ax.set_title(f"pH {ph} (real Gibbs energies, N={N_CONFORMERS})")
        fig.tight_layout()
        fig.savefig(OUT_DIR / f"landscape_1d_ph{ph}.png", dpi=200)
        plt.close(fig)

    # Overlay both pH values on one plot to show any pH-dependent shift
    from gpcr_energy_landscapes.energy_landscape import landscape_1d

    fig, ax = plt.subplots(figsize=(5.5, 4))
    for ph, color in zip(PH_VALUES, ["#3b6fa0", "#c0533e"]):
        energies = all_results[ph]
        cv = np.array([cv1_by_sid[s] for s in energies])
        g = np.array(list(energies.values()))
        landscape1d = landscape_1d(cv, gibbs=g, method="kde", grid_size=100)
        ax.plot(landscape1d["cv"], landscape1d["dG"], lw=2, color=color, label=f"pH {ph}")
    ax.set_xlabel("DRY-Arg <-> ionic-lock-partner distance (Å)")
    ax.set_ylabel(r"$\Delta G$ (kcal/mol)")
    ax.legend(frameon=False)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()
    fig.savefig(OUT_DIR / "landscape_1d_ph_overlay.png", dpi=200)
    plt.close(fig)

    summary = {
        "reference_structure": str(REFERENCE_PDB),
        "dry_arg_resnum": arg_resnum,
        "npxxy_tyr_resnum": tyr_resnum,
        "ionic_lock_partner_resnum": partner_resnum,
        "activation_states": state_by_sid,
        "pka_sample": dict(list(sorted(pka.items()))[:20]),
        "gibbs_kcal_mol_by_ph": all_results,
    }
    with open(OUT_DIR / "summary.json", "w") as f:
        json.dump(summary, f, indent=2, default=str)

    print(f"\nDone. Results in {OUT_DIR}")
    for ph, energies in all_results.items():
        vals = list(energies.values())
        print(f"  pH {ph}: G range [{min(vals):.1f}, {max(vals):.1f}] kcal/mol, mean {np.mean(vals):.1f}")


if __name__ == "__main__":
    main()
